# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GolfClassic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GolfClassic
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Firestore', '~> 6.2.0'
  pod 'Firebase/Auth', '~> 6.2.0'

  target 'GolfClassicTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GolfClassic-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GolfClassic-tvOS

  target 'GolfClassic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
